import { App } from './lib/types';

export const defaultApps: App[] = [
    {
        project_id: '1',
        project_name: 'Electronic Health Record',
        project_description: 'Access and manage patient health records',
        icon: 'file-text',
        url: '#',
        project_type: 'Clinical',
        low_project_name: '',
        permission: 0,
        project_cost: '',
        project_created_by: '',
        project_created_by_type: '',
        project_date_created: '',
        project_discoverable: false,
        project_favorite: 0,
        project_global: false,
        project_has_portal: false,
        project_portal_name: '',
        user_permission: 0,
    },
    {
        project_id: '2',
        project_name: 'Medical Logistics',
        project_description: 'Track and manage medical supplies and equipment',
        icon: 'package',
        url: '#',
        project_type: 'Logistics',
        low_project_name: '',
        permission: 0,
        project_cost: '',
        project_created_by: '',
        project_created_by_type: '',
        project_date_created: '',
        project_discoverable: false,
        project_favorite: 0,
        project_global: false,
        project_has_portal: false,
        project_portal_name: '',
        user_permission: 0,
    },
    {
        project_id: '3',
        project_name: 'Personnel Management',
        project_description: 'Manage military and civilian personnel records',
        icon: 'users',
        url: '#',
        project_type: 'Administration',
        low_project_name: '',
        permission: 0,
        project_cost: '',
        project_created_by: '',
        project_created_by_type: '',
        project_date_created: '',
        project_discoverable: false,
        project_favorite: 0,
        project_global: false,
        project_has_portal: false,
        project_portal_name: '',
        user_permission: 0,
    },
    {
        project_id: '4',
        project_name: 'Pharmacy System',
        project_description: 'Prescription management and tracking',
        icon: 'pill',
        url: '#',
        project_type: 'Clinical',
        low_project_name: '',
        permission: 0,
        project_cost: '',
        project_created_by: '',
        project_created_by_type: '',
        project_date_created: '',
        project_discoverable: false,
        project_favorite: 0,
        project_global: false,
        project_has_portal: false,
        project_portal_name: '',
        user_permission: 0,
    },
    {
        project_id: '5',
        project_name: 'Appointment Scheduler',
        project_description: 'Schedule and manage patient appointments',
        icon: 'calendar',
        url: '#',
        project_type: 'Clinical',
        low_project_name: '',
        permission: 0,
        project_cost: '',
        project_created_by: '',
        project_created_by_type: '',
        project_date_created: '',
        project_discoverable: false,
        project_favorite: 0,
        project_global: false,
        project_has_portal: false,
        project_portal_name: '',
        user_permission: 0,
    },
    {
        project_id: '6',
        project_name: 'Budget Tracker',
        project_description: 'Track and manage departmental budgets',
        icon: 'dollar-sign',
        url: '#',
        project_type: 'Administration',
        low_project_name: '',
        permission: 0,
        project_cost: '',
        project_created_by: '',
        project_created_by_type: '',
        project_date_created: '',
        project_discoverable: false,
        project_favorite: 0,
        project_global: false,
        project_has_portal: false,
        project_portal_name: '',
        user_permission: 0,
    },
    {
        project_id: '7',
        project_name: 'Training Portal',
        project_description: 'Access required training and education resources',
        icon: 'graduation-cap',
        url: '#',
        project_type: 'Education',
        low_project_name: '',
        permission: 0,
        project_cost: '',
        project_created_by: '',
        project_created_by_type: '',
        project_date_created: '',
        project_discoverable: false,
        project_favorite: 0,
        project_global: false,
        project_has_portal: false,
        project_portal_name: '',
        user_permission: 0,
    },
    {
        project_id: '8',
        project_name: 'Facility Management',
        project_description: 'Manage medical facilities and infrastructure',
        icon: 'building',
        url: '#',
        project_type: 'Logistics',
        low_project_name: '',
        permission: 0,
        project_cost: '',
        project_created_by: '',
        project_created_by_type: '',
        project_date_created: '',
        project_discoverable: false,
        project_favorite: 0,
        project_global: false,
        project_has_portal: false,
        project_portal_name: '',
        user_permission: 0,
    },
];
